[package]
name = "flat"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "2.0.1", features = ["full"] }
enumflags2 = "0.7.12"
indexmap = "2.9.0"
itertools = "0.14.0"
tabled = "0.19.0"
uuid = { version = "1.16.0", features = ["v4"] }
winnow = "0.7.6"
